spring:
    cloud:
        inetutils:
            preferred-networks: 127.0.0.1
eureka:
    instance:
        prefer-ip-address: true
    client:
        register-with-eureka: true
        fetch-registry: true
#开启熔断器
feign:
    hystrix:
        enabled: true
